### ISSUE TITLE
Projects Tracker

### ISSUE THREAD

**Issue by jaballogian** [Virtue-Digital-Indonesia/frontend-examples#1]
This issue is used to list and track the progress of each project.
Here are the projects:
1. Data Grid Based
- [ ] Data Grid Filters and Data Grid Table
- [ ] Object List with MUI Data Grid
2. Markers, Popups, and Clusters Based
- [ ] Markers, Popups, and Clusters with Leaflet
- [ ] Animation/moving Marker
3. Geofence Based
- [ ] Create, show, edit, and delete Geofences with Leaflet
4. Date Range Picker Based
- [ ] Date Range and Time Picker
